apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agw-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: us-docker.pkg.dev/solo-public/enterprise-agentgateway/charts
    chart: enterprise-agentgateway-crds
    targetRevision: v2.3.0-rc.1
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
