apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: agw-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jamesilse-solo/field-poc-kla-manifests.git
    targetRevision: gke
    path: manifests/base
  destination:
    server: https://kubernetes.default.svc
    namespace: agentgateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
