apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: "80.4.2"
    helm:
      valuesObject:
        alertmanager:
          enabled: false
        grafana:
          adminPassword: "prom-operator"
          grafana.ini:
            server:
              root_url: "%(protocol)s://%(domain)s/grafana/"
              serve_from_sub_path: true
          service:
            type: ClusterIP
            port: 3000
          sidecar:
            dashboards:
              enabled: true
              label: grafana_dashboard
              labelValue: "1"
              searchNamespace: monitoring
        nodeExporter:
          enabled: false
        prometheus:
          service:
            type: ClusterIP
          prometheusSpec:
            ruleSelectorNilUsesHelmValues: false
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
